### PR TITLE
Added SPACE and ENTER key to be acceptable keys to move to the NEXT

### PR DESCRIPTION
**Pull request by Kardelio**
Hey so when I first tried out shlide (which I LOVE by the way) before reading the instructions on how to move to the next slide I instinctively tried using the space bar and the enter key to try and move on (also the arrow keys but thats for another PR ;P ) and unfortunately these didn't work then I read the manual and saw N and P for 'next' and 'previous' which is ace but I thought maybe you would be interested in having the space key as an acceptable key to move to the next slide.
So that is exactly what this tiny change does.
When read with -rsn1 is used the space key and enter key appear as just blank strings '' so i simply added that.

I hope this is ok? Feel free to ignore this if it doesn't align with your vision for the project!

Again this is a awesome project and I really like it well done!

### CODE REVIEW

**Comment by icyphox** [comment]
Hey, thanks! Neckbeards like me tend to forget about the existence of
other -- non-vim-like -- ways to navigate. :D

> also the arrow keys but thats for another PR

Looking forward to this one as well. 

Just one more thing before I merge this -- can you push a commit
updating the readme? (line 9). Thanks again.

**Comment by Kardelio** [comment]
I can indeed! Bare with me ...

Also yessss VIM all the way 👍

**Comment by Kardelio** [comment]
@icyphox Updated the readme good sir! Hope its ok? 🕺

**Comment by oppiliappan** [comment]
looks good @Kardelio 

thank you for your contributions!

**Comment by Kardelio** [comment]
@NerdyPepper the pleasure is all mine! Its a really cool project to contribute to, so well done to you both!
I hope its ok I will probably try and contribute more in the coming weeks when i have time to have a tinker as I think this is really really ace! Hope thats ok?

**Comment by icyphox** [comment]
@Kardelio Thanks! By all means yes, feel free to shoot more PRs. :)

**Pull request merged**
